[project]
name = "prompt-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.42.2",
    "openai>=1.12.0",
    "python-dotenv>=1.0.0",
]
